openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
servers:
  - url: https://api.server.test/v1
paths:
  /deal:
    get:
      tags:
        - Deal
      summary: Get list of deals
      security:
        - BearerAuth: []
      responses:
        '200':
          description: List of deals retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Deal'
    post:
      tags:
        - Deal
      summary: Create a new deal
      description: Create a new hotel profile.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Deal' # Reference to the Hotel schema
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                User_id:
                  type: string
                  example: 613abc123def456789000000
                Hotel_id:
                  type: string
                  example: 623def456abc789012300000
                RoomType_id:
                  type: string
                  example: 634efg567hij890123400000
                status:
                  type: string
                  description: Status of the deal
                  enum:
                    - booking
                    - purchase
                    - cancelled
                    - active
                    - finished
                checkIn:
                  type: string
                  format: date-time
                  description: Check-in date for the deal
                checkOut:
                  type: string
                  format: date-time
                  description: Check-out date for the deal
      responses:
        '200':
          description: Deal created successfully
        '400':
          description: Invalid input

  /deal/{dealId}:
    get:
      tags:
        - Deal
      summary: Get one deal by id
      description: Retrieve a deal by its id.
      parameters:
        - in: path
          name: dealId
          schema:
            type: string
          required: true
          description: The name of the hotel to retrieve.
      security:
        - BearerAuth: []
      responses:
        '200':
          description: List of deals retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Deal'

  /deal/{hotelId}:
    get:
      tags:
        - Deal
      summary: Get deal by hotelId
      description: Retrieve deals by hotelId.
      parameters:
        - in: path
          name: hotelId
          schema:
            type: string
          required: true
          description: The ID of the hotel to retrieve deals for.
      security:
        - BearerAuth: []
      responses:
        '200':
          description: List of deals retrieved successfully
          content:
            application/json:
              schema:
                type: object
                example:
                  name: Hotel Example
                  email: hotel@example.com
                  users:
                    - _id: user123
                      firstName: John
                      lastName: Doe
                      email: john@example.com
                      deal:
                        checkIn: '2023-08-25T12:00:00Z'
                        checkOut: '2023-08-30T12:00:00Z'
                        status: active
                        room:
                          name: Deluxe Room
                          price: 200
                          stock: 5
components:
  schemas:
    Deal:
      type: object
      properties:
        User_id:
          type: string
          description: ID of the user associated with the deal
        RoomType_id:
          type: string
          description: ID of the room type associated with the deal
        status:
          type: string
          description: Status of the deal
          enum:
            - booking
            - purchase
            - cancelled
            - active
            - finished
        checkIn:
          type: string
          format: date-time
          description: Check-in date for the deal
        checkOut:
          type: string
          format: date-time
          description: Check-out date for the deal
      example:
        User_id: 603f650a325e8e001c93af46
        RoomType_id: 603f650a325e8e001c93af47
        status: active
        checkIn: '2023-08-23T14:00:00Z'
        checkOut: '2023-08-25T12:00:00Z'

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
