openapi: 3.0.0
info:
  title: User API
  version: 1.0.0
paths:
  /hotel:
    get:
      tags:
        - Hotel
      summary: Get hotel by name
      description: Retrieve a hotel by its name.
      parameters:
        - in: query
          name: name
          schema:
            type: string
          required: true
          description: The name of the hotel to retrieve.
      responses:
        '200':
          description: Hotel found successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hotel'
        '400':
          description: Bad request

    post:
      tags:
        - Hotel
      summary: Create a new hotel
      description: Create a new hotel profile.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Hotel' # Reference to the Hotel schema
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Name of the hotel
                email:
                  type: string
                  format: email
                  description: Email address of the hotel
                images:
                  type: array
                  description: List of images related to the hotel
                  items:
                    type: string
                    format: url
                    description: URL of an image
                  maxItems: 5
                category:
                  type: number
                  description: Category of the hotel
                services:
                  type: array
                  description: List of services offered by the hotel
                  items:
                    type: string
                    enum:
                      - all inclusive
                      - breakfast
                      - lunch
                      - dinner
                      - bar
                  default: ['no services']
                country:
                  type: string
                  description: Country where the hotel is located
                state:
                  type: string
                  description: State where the hotel is located
                address:
                  type: string
                  description: Address of the hotel
                room:
                  type: object
                  properties:
                    name:
                      type: string
                      description: Name of the hotel room
                    price:
                      type: number
                      description: Price of the hotel room
                    stock:
                      type: number
                      description: Available stock of the hotel room
                roomService:
                  type: boolean
                  description: Indicates if room service is available
                wifi:
                  type: boolean
                  description: Indicates if WiFi is available
                isActive:
                  type: boolean
                  description: Indicates if the hotel is active
      responses:
        '201':
          description: Hotel created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hotel' # Reference to the Hotel schema
        '400':
          description: Bad request
        '500':
          description: Internal server error

components:
  schemas:
    Hotel:
      type: object
      properties:
        name:
          type: string
          description: Name of the hotel
        email:
          type: string
          format: email
          description: Email address of the hotel
        images:
          type: array
          description: List of images related to the hotel
          items:
            type: object
            properties:
              id:
                type: string
                description: ID of the image
              src:
                type: string
                description: URL of the image
              type:
                type: string
                description: Type of the image
          maxItems: 5
        category:
          type: number
          description: Category of the hotel
        services:
          type: array
          description: List of services offered by the hotel
          items:
            type: string
            enum:
              - all inclusive
              - breakfast
              - lunch
              - dinner
              - bar
          default: ['no services']
        country:
          type: string
          description: Country where the hotel is located
        state:
          type: string
          description: State where the hotel is located
        address:
          type: string
          description: Address of the hotel
        room:
          type: object
          properties:
            name:
              type: string
              description: Name of the hotel room
            price:
              type: number
              description: Price of the hotel room
            stock:
              type: number
              description: Available stock of the hotel room
        roomService:
          type: boolean
          description: Indicates if room service is available
        wifi:
          type: boolean
          description: Indicates if WiFi is available
        isActive:
          type: boolean
          description: Indicates if the hotel is active
        createdAt:
          type: string
          format: date-time
          description: Timestamp of when the hotel was created
        updatedAt:
          type: string
          format: date-time
          description: Timestamp of when the hotel was last updated
      example:
        name: Hilton Hotel
        email: hilton@gmail.com.us
        images:
          - id: 1
            src: https://example.com/image1.jpg
            type: exterior
          - id: 2
            src: https://example.com/image2.jpg
            type: interior
        category: 4
        services:
          - breakfast
          - bar
        country: United States
        state: California
        address: 123 Example Street
        room:
          name: Deluxe Room
          price: 200
          stock: 10
        roomService: true
        wifi: true
        isActive: true
        createdAt: '2023-08-23T12:34:56Z'
        updatedAt: '2023-08-23T14:45:32Z'
